services:
  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    container_name: pfmongodb
    ports:
      - "27017:27017"
  redis:
    image: "redis/redis-stack-server:latest"
    container_name: pfredis
    ports:
      - "6379:6379"
  api:
    build: .
    container_name: pfbackend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /API
    depends_on:
      - mongodb
      - redis
    environment:
      - PF_MONGO_CONNECTION=${PF_MONGO_CONNECTION}
      - PF_TBA_API_KEY=${PF_TBA_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PF_TBA_POLLING=${PF_TBA_POLLING}
      - PF_TBA_POLLING_INTERVAL=${PF_TBA_POLLING_INTERVAL}
      - PF_EDIT_PASSWORD=${PF_EDIT_PASSWORD}
  app:
    build: ./APP
    ports:
      - "3000:3000"
    container_name: pffrontend
    develop:
      watch:
        - action: sync
          path: .
          target: /APP