// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import '../models/match_2024.dart';
import '../models/match_prediction_2024.dart';
import '../models/team_stats_2024.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'match_details_2024.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'match_details_2024.g.dart';

@freezed
class MatchDetails2024 with _$MatchDetails2024 {
  const factory MatchDetails2024({
    required Match2024 match,
    required MatchPrediction2024 prediction,
    required List<TeamStats2024> red_teams,
    required List<TeamStats2024> blue_teams,
  }) = _MatchDetails2024;

  factory MatchDetails2024.fromJson(Map<String, Object?> json) =>
      _$MatchDetails2024FromJson(json);
}
