// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import '../models/match_2025.dart';
import '../models/match_prediction_2025.dart';
import '../models/team_stats_2025.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'match_details_2025.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'match_details_2025.g.dart';

@freezed
class MatchDetails2025 with _$MatchDetails2025 {
  const factory MatchDetails2025({
    required Match2025 match,
    required MatchPrediction2025? prediction,
    required List<TeamStats2025>? red_teams,
    required List<TeamStats2025>? blue_teams,
  }) = _MatchDetails2025;

  factory MatchDetails2025.fromJson(Map<String, Object?> json) =>
      _$MatchDetails2025FromJson(json);
}
