// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import '../models/match_2026.dart';
import '../models/match_prediction_2026.dart';
import '../models/team_stats_2026.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'match_details_2026.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'match_details_2026.g.dart';

@freezed
class MatchDetails2026 with _$MatchDetails2026 {
  const factory MatchDetails2026({
    required Match2026 match,
    required MatchPrediction2026? prediction,
    required List<TeamStats2026>? red_teams,
    required List<TeamStats2026>? blue_teams,
  }) = _MatchDetails2026;

  factory MatchDetails2026.fromJson(Map<String, Object?> json) =>
      _$MatchDetails2026FromJson(json);
}
