// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'team_stats_2024.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'team_stats_2024.g.dart';

@freezed
class TeamStats2024 with _$TeamStats2024 {
  const factory TeamStats2024({
    required int rank,
    required int match_count,
    required double OPR,
    required double endgame_points,
    required double teleop_points,
    required double auto_points,
    required double notes,
    required double teleop_pass,
    required double teleop_notes,
    required double harmony_points,
    required double speaker_total,
    required double amp_total,
    required double trap_points,
    required double trap,
    required double auto_notes,
    required double climbing_points,
    required double climbing,
    required double mobility,
    required double death_rate,
    required double parking,
    required double auto_speaker,
    required double auto_amp,
    required double teleop_speaker,
    required double teleop_amped_speaker,
    required double teleop_amp,
    required double harmony,
    required double mic,
    required double coopertition,
    required double simulated_rp,
    required double simulated_rank,
    required double pass,
    required String key,
    required String team_number,
  }) = _TeamStats2024;

  factory TeamStats2024.fromJson(Map<String, Object?> json) =>
      _$TeamStats2024FromJson(json);
}
