// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'team_stats_2025.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TeamStats2025Impl _$$TeamStats2025ImplFromJson(Map<String, dynamic> json) =>
    _$TeamStats2025Impl(
      historical: json['historical'] as bool,
      key: json['key'] as String,
      rank: (json['rank'] as num).toInt(),
      team_number: json['team_number'] as String,
      match_count: (json['match_count'] as num).toDouble(),
      OPR: (json['OPR'] as num).toDouble(),
      endgame_points: (json['endgame_points'] as num).toDouble(),
      teleop_points: (json['teleop_points'] as num).toDouble(),
      auto_points: (json['auto_points'] as num).toDouble(),
      l_4_total: (json['l_4_total'] as num).toDouble(),
      l_3_total: (json['l_3_total'] as num).toDouble(),
      l_2_total: (json['l_2_total'] as num).toDouble(),
      l_1_total: (json['l_1_total'] as num).toDouble(),
      total_pieces: (json['total_pieces'] as num).toDouble(),
      algae_total: (json['algae_total'] as num).toDouble(),
      algae_points: (json['algae_points'] as num).toDouble(),
      coral_total: (json['coral_total'] as num).toDouble(),
      coral_points: (json['coral_points'] as num).toDouble(),
      teleop_coral_points: (json['teleop_coral_points'] as num).toDouble(),
      teleop_coral: (json['teleop_coral'] as num).toDouble(),
      auto_coral_points: (json['auto_coral_points'] as num).toDouble(),
      auto_coral: (json['auto_coral'] as num).toDouble(),
      shallow_climb_rate: (json['shallow_climb_rate'] as num).toDouble(),
      deep_climb_rate: (json['deep_climb_rate'] as num).toDouble(),
      climbing_points: (json['climbing_points'] as num).toDouble(),
      mobility: (json['mobility'] as num).toDouble(),
      death_rate: (json['death_rate'] as num).toDouble(),
      parking: (json['parking'] as num).toDouble(),
      auto_scoring_l_1: (json['auto_scoring_l_1'] as num).toDouble(),
      auto_scoring_l_2: (json['auto_scoring_l_2'] as num).toDouble(),
      auto_scoring_l_3: (json['auto_scoring_l_3'] as num).toDouble(),
      auto_scoring_l_4: (json['auto_scoring_l_4'] as num).toDouble(),
      teleop_scoring_l_1: (json['teleop_scoring_l_1'] as num).toDouble(),
      teleop_scoring_l_2: (json['teleop_scoring_l_2'] as num).toDouble(),
      teleop_scoring_l_3: (json['teleop_scoring_l_3'] as num).toDouble(),
      teleop_scoring_l_4: (json['teleop_scoring_l_4'] as num).toDouble(),
      net: (json['net'] as num).toDouble(),
      processor: (json['processor'] as num).toDouble(),
      foul_points: (json['foul_points'] as num).toDouble(),
      coopertition: (json['coopertition'] as num).toDouble(),
      simulated_rp: (json['simulated_rp'] as num).toInt(),
      simulated_rank: (json['simulated_rank'] as num).toInt(),
    );

Map<String, dynamic> _$$TeamStats2025ImplToJson(_$TeamStats2025Impl instance) =>
    <String, dynamic>{
      'historical': instance.historical,
      'key': instance.key,
      'rank': instance.rank,
      'team_number': instance.team_number,
      'match_count': instance.match_count,
      'OPR': instance.OPR,
      'endgame_points': instance.endgame_points,
      'teleop_points': instance.teleop_points,
      'auto_points': instance.auto_points,
      'l_4_total': instance.l_4_total,
      'l_3_total': instance.l_3_total,
      'l_2_total': instance.l_2_total,
      'l_1_total': instance.l_1_total,
      'total_pieces': instance.total_pieces,
      'algae_total': instance.algae_total,
      'algae_points': instance.algae_points,
      'coral_total': instance.coral_total,
      'coral_points': instance.coral_points,
      'teleop_coral_points': instance.teleop_coral_points,
      'teleop_coral': instance.teleop_coral,
      'auto_coral_points': instance.auto_coral_points,
      'auto_coral': instance.auto_coral,
      'shallow_climb_rate': instance.shallow_climb_rate,
      'deep_climb_rate': instance.deep_climb_rate,
      'climbing_points': instance.climbing_points,
      'mobility': instance.mobility,
      'death_rate': instance.death_rate,
      'parking': instance.parking,
      'auto_scoring_l_1': instance.auto_scoring_l_1,
      'auto_scoring_l_2': instance.auto_scoring_l_2,
      'auto_scoring_l_3': instance.auto_scoring_l_3,
      'auto_scoring_l_4': instance.auto_scoring_l_4,
      'teleop_scoring_l_1': instance.teleop_scoring_l_1,
      'teleop_scoring_l_2': instance.teleop_scoring_l_2,
      'teleop_scoring_l_3': instance.teleop_scoring_l_3,
      'teleop_scoring_l_4': instance.teleop_scoring_l_4,
      'net': instance.net,
      'processor': instance.processor,
      'foul_points': instance.foul_points,
      'coopertition': instance.coopertition,
      'simulated_rp': instance.simulated_rp,
      'simulated_rank': instance.simulated_rank,
    };
