// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tournament.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tournament.g.dart';

@freezed
class Tournament with _$Tournament {
  const factory Tournament({
    required String key,
    required String display,
    required String page,
    required String start,
    required String end,
  }) = _Tournament;

  factory Tournament.fromJson(Map<String, Object?> json) =>
      _$TournamentFromJson(json);
}
