const year = 2025;

const Map<String, String> eventNames = {
  '${year}alhu': '${year} Rocket City Regional [${year}alhu]',
  '${year}arc': '${year} Archimedes Division [${year}arc]',
  '${year}arli': '${year} Arkansas Regional [${year}arli]',
  '${year}audd': '${year} Duel Down Under [${year}audd]',
  '${year}ausc': '${year} Southern Cross Regional [${year}ausc]',
  '${year}auwarp': '${year} West Australian Robotics Playoffs [${year}auwarp]',
  '${year}azfg': '${year} Arizona North Regional [${year}azfg]',
  '${year}azgl': '${year} Arizona East Regional [${year}azgl]',
  '${year}azrl1': '${year} Arizona Robotics League Qualifier 1 [${year}azrl1]',
  '${year}azrl2': '${year} Arizona Robotics League Qualifier 2 [${year}azrl2]',
  '${year}azrl3': '${year} Arizona Robotics League Qualifier 3 [${year}azrl3]',
  '${year}azrl4': '${year} Arizona Robotics League Qualifier 4 [${year}azrl4]',
  '${year}azrl5': '${year} Arizona Robotics League Qualifier 5 [${year}azrl5]',
  '${year}bc': '${year} BattleCry at WPI [${year}bc]',
  '${year}bcvi': '${year} Canadian Pacific Regional [${year}bcvi]',
  '${year}brba': '${year} Regional Brazil [${year}brba]',
  '${year}brsp': '${year} Regional Brazil - São Paulo [${year}brsp]',
  '${year}caab': '${year} Alberta Canadian Rockies Open @ KDays [${year}caab]',
  '${year}caav': '${year} Aerospace Valley Regional [${year}caav]',
  '${year}cabe': '${year} East Bay Regional [${year}cabe]',
  '${year}cacc': '${year} Capital City Classic [${year}cacc]',
  '${year}cacg': '${year} CalGames [${year}cacg]',
  '${year}cada': '${year} Sacramento Regional [${year}cada]',
  '${year}cafb': '${year} Fairbotics Pacific Showdown [${year}cafb]',
  '${year}cafr': '${year} Central Valley Regional [${year}cafr]',
  '${year}cala': '${year} Los Angeles Regional [${year}cala]',
  '${year}camb': '${year} Pinnacles Regional [${year}camb]',
  '${year}caoc': '${year} Orange County Regional [${year}caoc]',
  '${year}caph': '${year} Hueneme Port Regional [${year}caph]',
  '${year}capt': '${year} Contra Costa Regional [${year}capt]',
  '${year}casd': '${year} San Diego Regional [${year}casd]',
  '${year}casf': '${year} San Francisco Regional [${year}casf]',
  '${year}casj': '${year} Silicon Valley Regional [${year}casj]',
  '${year}cass': '${year} SoCal Showdown [${year}cass]',
  '${year}catt': '${year} Tidal Tumble [${year}catt]',
  '${year}cave': '${year} Ventura County Regional [${year}cave]',
  '${year}cc': '${year} Chezy Champs [${year}cc]',
  '${year}chcmp': '${year} Chesapeake District Championship [${year}chcmp]',
  '${year}cisw0': '${year} Becker Week Zero [${year}cisw0]',
  '${year}cisw02': '${year} Becker Week Zero Day Two [${year}cisw02]',
  '${year}cmptx': '${year} Einstein Field [${year}cmptx]',
  '${year}cmrc': '${year} CMRC Championship [${year}cmrc]',
  '${year}cnsh': '${year} Shanghai Regional [${year}cnsh]',
  '${year}cocs': '${year} Colorado Scrimmage [${year}cocs]',
  '${year}code': '${year} Colorado Regional [${year}code]',
  '${year}cokc': '${year} Kendrick Castillo Memorial Tournament [${year}cokc]',
  '${year}ctgla': '${year} CIAC CT State Championship [${year}ctgla]',
  '${year}cthar': '${year} NE District Hartford Event [${year}cthar]',
  '${year}ctwat': '${year} NE District Waterbury Event [${year}ctwat]',
  '${year}cur': '${year} Curie Division [${year}cur]',
  '${year}dal': '${year} Daly Division [${year}dal]',
  '${year}flhom': '${year} Pirates Pillage [${year}flhom]',
  '${year}flor': '${year} Orlando Regional [${year}flor]',
  '${year}flta': '${year} Tallahassee Regional [${year}flta]',
  '${year}flwp': '${year} South Florida Regional [${year}flwp]',
  '${year}gaalb': '${year} PCH District Albany Event [${year}gaalb]',
  '${year}gacmp': '${year} Peachtree District Championship [${year}gacmp]',
  '${year}gadal': '${year} PCH District Dalton Event [${year}gadal]',
  '${year}gagai': '${year} PCH District Gainesville Event [${year}gagai]',
  '${year}gagwi': '${year} PCH District Gwinnett Event [${year}gagwi]',
  '${year}gal': '${year} Galileo Division [${year}gal]',
  '${year}gasta': '${year} PCH District Statesboro Event [${year}gasta]',
  '${year}hiho': '${year} Hawaii Regional [${year}hiho]',
  '${year}hop': '${year} Hopper Division [${year}hop]',
  '${year}iacf': '${year} Iowa Regional [${year}iacf]',
  '${year}idbo': '${year} Idaho Regional [${year}idbo]',
  '${year}ilch': '${year} Midwest Regional [${year}ilch]',
  '${year}ilpe': '${year} Central Illinois Regional [${year}ilpe]',
  '${year}ilrr': '${year} Rock River Off-Season Competition [${year}ilrr]',
  '${year}iltrr': '${year} Roboteer Rumble [${year}iltrr]',
  '${year}incmp': '${year} Indiana State Championship [${year}incmp]',
  '${year}inkok': '${year} FIN District Kokomo Event [${year}inkok]',
  '${year}inlaf': '${year} FIN District Lafayette Event [${year}inlaf]',
  '${year}inmis': '${year} FIN District Mishawaka Event [${year}inmis]',
  '${year}inwas': '${year} FIN District Washington Event [${year}inwas]',
  '${year}ipr': '${year} Pregional by ORBIT [${year}ipr]',
  '${year}iri': '${year} Indiana Robotics Invitational [${year}iri]',
  '${year}iscmp': '${year} Israel District Championship [${year}iscmp]',
  '${year}isde1': '${year} ISR District Event #1 [${year}isde1]',
  '${year}isde2': '${year} ISR District Event #2 [${year}isde2]',
  '${year}isde3': '${year} ISR District Event #3 [${year}isde3]',
  '${year}isde4': '${year} ISR District Event #4 [${year}isde4]',
  '${year}joh': '${year} Johnson Division [${year}joh]',
  '${year}ksla': '${year} Heartland Regional [${year}ksla]',
  '${year}kylou': '${year} RiverBOaT Rumble [${year}kylou]',
  '${year}lake': '${year} Bayou Regional [${year}lake]',
  '${year}laman': '${year} Northshore Knockout [${year}laman]',
  '${year}mabos': '${year} NE District Greater Boston Event [${year}mabos]',
  '${year}macmp': '${year} MA State Championship [${year}macmp]',
  '${year}matb': '${year} New England Robotics Derby [${year}matb]',
  '${year}mawne': '${year} NE District Western NE Event [${year}mawne]',
  '${year}mawor': '${year} NE District WPI Event [${year}mawor]',
  '${year}mdbet': '${year} CHS District Bethesda MD Event [${year}mdbet]',
  '${year}mdpas': '${year} CHS District Pasadena MD Event [${year}mdpas]',
  '${year}mdsev': '${year} CHS District Severn MD Event [${year}mdsev]',
  '${year}mefal': '${year} NE District Southern Maine Event [${year}mefal]',
  '${year}melew': '${year} NE District Pine Tree Event [${year}melew]',
  '${year}mibat': '${year} FIM District Battle Creek Event [${year}mibat]',
  '${year}mibel': '${year} FIM District Belleville Event [${year}mibel]',
  '${year}miber': '${year} FIM District Berrien Springs Event [${year}miber]',
  '${year}mibig': '${year} FIM District Ferris State Event [${year}mibig]',
  '${year}mibkn':
      '${year} FIM District Jackson at Columbia Event [${year}mibkn]',
  '${year}mibro': '${year} FIM District Woodhaven Event [${year}mibro]',
  '${year}micmp': '${year} Michigan State Championship [${year}micmp]',
  '${year}micmp1':
      '${year} Michigan State Championship - DTE Energy Foundation Division [${year}micmp]',
  '${year}micmp2':
      '${year} Michigan State Championship - Hemlock Semiconductor Division [${year}micmp2]',
  '${year}micmp3':
      '${year} Michigan State Championship - Consumers Energy Division [${year}micmp3]',
  '${year}micmp4':
      '${year} Michigan State Championship - Aptiv Division [${year}micmp4]',
  '${year}midet': '${year} FIM District Renaissance Event [${year}midet]',
  '${year}midtr': '${year} FIM District Wayne State Event [${year}midtr]',
  '${year}miesc': '${year} FIM District Escanaba Event [${year}miesc]',
  '${year}mifer': '${year} FIM District Ferndale Event [${year}mifer]',
  '${year}mifli':
      '${year} Kettering All-Star Alliance Invitational [${year}mifli]',
  '${year}mifli1': '${year} Kettering Kickoff (Day 1) [${year}mifli1]',
  '${year}mifli2': '${year} Kettering Kickoff (Day 2) [${year}mifli2]',
  '${year}mifli3': '${year} Kettering Kickoff (Day 3) [${year}mifli3]',
  '${year}mike2':
      '${year} FIM District Kettering University Event #2 [${year}mike2]',
  '${year}miken': '${year} FIM District Kentwood Event [${year}miken]',
  '${year}miket':
      '${year} FIM District Kettering University Event #1 [${year}miket]',
  '${year}mil': '${year} Milstein Division [${year}mil]',
  '${year}milac': '${year} FIM District Lake City Event [${year}milac]',
  '${year}miliv': '${year} FIM District Livonia Event [${year}miliv]',
  '${year}milsu': '${year} FIM District LSSU Event [${year}milsu]',
  '${year}mimas': '${year} FIM District Mason Event [${year}mimas]',
  '${year}mimcc': '${year} FIM District Macomb Event [${year}mimcc]',
  '${year}mimi2': '${year} Great Lakes Bay Bot Bash [${year}mimi2]',
  '${year}mimid': '${year} FIM District Midland Event [${year}mimid]',
  '${year}mimil': '${year} FIM District Milford Event [${year}mimil]',
  '${year}mimtp': '${year} FIM District Mt. Pleasant Event [${year}mimtp]',
  '${year}mimus': '${year} FIM District Muskegon Event [${year}mimus]',
  '${year}miro': '${year} That ONE Off-Season [${year}miro]',
  '${year}mirr': '${year} Rainbow Rumble [${year}mirr]',
  '${year}misal': '${year} FIM District Saline Event [${year}misal]',
  '${year}misjo': '${year} FIM District St. Joseph Event [${year}misjo]',
  '${year}mitry': '${year} FIM District Troy Event [${year}mitry]',
  '${year}mitvc': '${year} FIM District Traverse City Event [${year}mitvc]',
  '${year}miwmi': '${year} FIM District West Michigan Event [${year}miwmi]',
  '${year}miwrc': '${year} Wolverine Robotics Competition [${year}miwrc]',
  // Halfway
  '${year}mksc': '${year} MoKan State Championship [${year}mksc]',
  '${year}mmr': '${year} Minne Mini Regional [${year}mmr]',
  '${year}mnbt': '${year} Blue Twilight Week Zero [${year}mnbt]',
  '${year}mndu': '${year} Lake Superior Regional [${year}mndu]',
  '${year}mndu2': '${year} Northern Lights Regional [${year}mndu2]',
  '${year}mnkk': '${year} KnightKrawler Week Zero [${year}mnkk]',
  '${year}mnmi': '${year} Minnesota 10,000 Lakes Regional [${year}mnmi]',
  '${year}mnmi2': '${year} Minnesota Granite City Regional [${year}mnmi]',
  '${year}mnsar': '${year} Mississippi Mayhem [${year}mnsar]',
  '${year}mnsp': '${year} Minnesota State Championship Scrimmage [${year}mnsp]',
  '${year}mnst':
      '${year} Minnesota State High School League Championship [${year}mnst]',
  '${year}mnum': '${year} Minnesota North Star Regional [${year}mnum]',
  '${year}mogw': '${year} Gateway Robotics Challenge (GRC) [${year}mogw]',
  '${year}mokc': '${year} Greater Kansas City Regional [${year}mokc]',
  '${year}mose': '${year} Central Missouri Regional [${year}mose]',
  '${year}mosl': '${year} St. Louis Regional [${year}mosl]',
  '${year}mrcmp': '${year} Mid-Atlantic District Championship [${year}mrcmp]',
  '${year}mslr': '${year} Magnolia Regional [${year}mslr]',
  '${year}mxle': '${year} Regional Leon [${year}mxle]',
  '${year}mxmo': '${year} Regional Monterrey [${year}mxmo]',
  '${year}mxto': '${year} Regional Laguna [${year}mxtp]',
  '${year}ncash': '${year} FNC District UNC Asheville Event [${year}ncash]',
  '${year}nccat': '${year} FNC District Catawba County Event [${year}nccat]',
  '${year}nccmp': '${year} North Carolina State Championship [${year}nccmp]',
  '${year}ncgre': '${year} FNC District Pitt County Event [${year}ncgre]',
  '${year}nci': '${year} Northern California Invitational [${year}nci]',
  '${year}ncmec':
      '${year} FNC District Mecklenburg County Event [${year}ncmec]',
  '${year}ncpem': '${year} FNC District UNC Pembroke Event [${year}ncpem]',
  '${year}ncrc': '${year} North Catholic Robotics Competition [${year}ncrc]',
  '${year}ncspr': '${year} THOR East [${year}ncspr]',
  '${year}ncth2': '${year} THOR West [${year}ncth2]',
  '${year}ncwak': '${year} FNC District Wake County Event [${year}ncwak]',
  '${year}ndgf': '${year} Great Northern Regional [${year}ndgf]',
  '${year}necmp':
      '${year} New England FIRST District Championship [${year}necmp]',
  '${year}necmp2':
      '${year} New England FIRST District Championship - Sosik Division [${year}necmp2]',
  '${year}new': '${year} Newton Division [${year}new]',
  '${year}nhdur': '${year} NE District UNH Event [${year}nhdur]',
  '${year}nhmm': '${year} Mayhem In Merrimack [${year}nhmm]',
  '${year}nhrr': '${year} RiverRage 28 [${year}nhrr]',
  '${year}nhsal': '${year} NE District Granite State Event [${year}nhsal]',
  '${year}njdd': '${year} Duel on the Delaware [${year}njdd]',
  '${year}njfla': '${year} FMA District Mount Olive Event [${year}njfla]',
  '${year}njrob': '${year} FMA District Robbinsville Event [${year}njrob]',
  '${year}njrr': '${year} Robot Rumble at RoboCon New Jersey [${year}njrr]',
  '${year}njski': '${year} FMA District Montgomery Event [${year}njski]',
  '${year}njtab': '${year} FMA District Seneca Event [${year}njtab]',
  '${year}njwas': '${year} FMA District Warren Hills Event [${year}njwas]',
  '${year}nmrc': '${year} NMRC Open [${year}nmrc]',
  '${year}nmrc2': '${year} NMRC Championship [${year}nmrc2]',
  '${year}ntwc': '${year} New Taipei City Regional [${year}ntwc]',
  '${year}nvlv': '${year} Las Vegas Regional [${year}nvlv]',
  '${year}nycrr': '${year} NYC Robo Replay  [${year}nycrr]',
  '${year}nyli2': '${year} Long Island Regional [${year}nyli2]',
  '${year}nyny': '${year} New York City Regional [${year}nyny]',
  '${year}nyro': '${year} Finger Lakes Regional [${year}nyro]',
  '${year}nyro2': '${year} Flower City Frenzy [${year}nyro2]',
  '${year}nyrr': '${year} Rah Cha Cha Ruckus [${year}nyrr]',
  '${year}nysu': '${year} Hudson Valley Regional [${year}nysu]',
  '${year}nytr': '${year} New York Tech Valley Regional [${year}nytr]',
  '${year}ohcl': '${year} Buckeye Regional [${year}ohcl]',
  '${year}ohmv': '${year} Miami Valley Regional [${year}ohmv]',
  '${year}ohsc': '${year} Ohio State Championship [${year}ohsc]',
  '${year}okok': '${year} Oklahoma Regional [${year}okok]',
  '${year}oktu': '${year} Green Country Regional [${year}oktu]',
  '${year}oncmp': '${year} Ontario Provincial Championship [${year}oncmp]',
  '${year}oncmp1':
      '${year} Ontario Provincial Championship - Science Division [${year}oncmp1]',
  '${year}oncmp2':
      '${year} Ontario Provincial Championship - Technology Division [${year}oncmp2]',
  '${year}onham': '${year} District McMaster University [${year}onham]',
  '${year}onnew': '${year} ONT District Newmarket Event [${year}onnew]',
  '${year}onnob': '${year} ONT District North Bay Event [${year}onnob]',
  '${year}onosh': '${year} ONT District Durham College Event [${year}onosh]',
  '${year}onsca':
      '${year} ONT District Centennial College Event [${year}onsca]',
  '${year}onsca1': '${year} Robots@Mary Ward Day 1 [${year}onsca1]',
  '${year}onsca2': '${year} Robots@Mary Ward Day 2 [${year}onsca2]',
  '${year}ontor':
      '${year} ONT District Humber Polytechnic Event [${year}ontor]',
  '${year}onwat':
      '${year} ONT District University of Waterloo Event [${year}onwat]',
  '${year}onwel': '${year} ONT District Niagara College Event [${year}onwel]',
  '${year}onwin':
      '${year} ONT District Windsor Essex Great Lake Event [${year}onwin]',
  '${year}orore': '${year} PNW District Clackamas Academy Event [${year}orore]',
  '${year}orsal': '${year} PNW District Oregon State Fair Event [${year}orsal]',
  '${year}orwil': '${year} PNW District Wilsonville Event [${year}orwil]',
  '${year}paben': '${year} FMA District Bensalem Event [${year}paben]',
  '${year}paca': '${year} Greater Pittsburgh Regional [${year}paca]',
  '${year}pahat': '${year} FMA District Hatboro-Horsham Event [${year}pahat]',
  '${year}paphi':
      '${year} FMA District Springside Chestnut Hill Event [${year}paphi]',
  '${year}pasc': '${year} Steel City Robotics Alliance Week 0 [${year}pasc]',
  '${year}pawar': '${year} FMA District Centennial Event [${year}pawar]',
  '${year}pncmp':
      '${year} Pacific Northwest FIRST District Championship [${year}pncmp]',
  '${year}qcmo': '${year} Festival de Robotique Regional [${year}qcmo]',
  '${year}rikin': '${year} NE District URI Event [${year}rikin]',
  '${year}rsr': '${year} The DOW Red Stick Rumble [${year}rsr]',
  '${year}sccha': '${year} FSC District North Charleston Event [${year}sccha]',
  '${year}sccmp':
      '${year} South Carolina State Championship presented by Magna [${year}sccmp]',
  '${year}schar': '${year} FSC District Hartsville Event [${year}schar]',
  '${year}srsd': '${year} Shamrock Showdown [${year}srsd]',
  '${year}sunshow': '${year} Sunset Showdown [${year}sunshow]',
  '${year}tacy': '${year} Taiwan Playoff [${year}tacy]',
  '${year}tnkn': '${year} Smoky Mountains Regional [${year}tnkn]',
  '${year}trdar': '${year} Darİca Robocube Off-Season [${year}trdar]',
  '${year}tris': '${year} Cezeri Robot Ligi Week 0 [${year}tris]',
  '${year}tuak': '${year} Ankara Regional [${year}tuak]',
  '${year}tuhc': '${year} Haliç Regional [${year}tuhc]',
  '${year}tuis': '${year} İstanbul Regional [${year}tuis]',
  '${year}tuis2': '${year} Bosphorus Regional [${year}tuis2]',
  '${year}tuis3': '${year} Marmara Regional [${year}tuis3]',
  '${year}txama': '${year} FIT District Amarillo Event [${year}txama]',
  '${year}txbc': '${year} Buc Days [${year}txbc]',
  '${year}txbel': '${year} FIT District Belton Event [${year}txbel]',
  '${year}txcle':
      '${year} FIT District Space City @ Friendswood Event [${year}txcle]',
  '${year}txcmp': '${year} FIRST In Texas District Championship [${year}txcmp]',
  '${year}txcmp1':
      '${year}FIRST In Texas District Championship - Mercury Division [${year}txcmp1]',
  '${year}txcmp2':
      '${year} FIRST In Texas District Championship - Apollo Division [${year}txcmp2]',
  '${year}txdri':
      '${year} Dripping Springs Robotics Invitational Palooza [${year}txdri]',
  '${year}txfor': '${year} FIT District Fort Worth Event [${year}txfor]',
  '${year}txhou': '${year} FIT District Houston Event [${year}txhou]',
  '${year}txhou1': '${year} Texas Robotics Invitational [${year}txhou1]',
  '${year}txman': '${year} FIT District Manor Event [${year}txman]',
  '${year}txpla': '${year} FIT District Plano Event [${year}txpla]',
  '${year}txsan': '${year} FIT District San Antonio Event [${year}txsan]',
  '${year}txtom': '${year} FIT District Tomball Event [${year}txtom]',
  '${year}txvic': '${year} FIT District Victoria Event [${year}txvic]',
  '${year}txwac': '${year} FIT District Waco Event [${year}txwac]',
  '${year}utwv': '${year} Utah Regional [${year}utwv]',
  '${year}vaale': '${year} CHS District Alexandria VA Event [${year}vaale]',
  '${year}vabla': '${year} CHS District Blacksburg VA Event [${year}vable]',
  '${year}vabrb': '${year} Blue Ridge Brawl [${year}vabrb]',
  '${year}vagle': '${year} CHS District Glen Allen VA Event [${year}vagle]',
  '${year}valge2': '${year} Rumble #10 [${year}vagle]',
  '${year}vapor': '${year} CHS District Portsmouth VA Event [${year}vapor]',
  '${year}vtbur': '${year} NE District UVM Event [${year}vtbur]',
  '${year}waahs': '${year} PNW District Auburn Event [${year}waahs]',
  '${year}wabon': '${year} PNW District Bonney Lake Event [${year}wabon]',
  '${year}wasam': '${year} PNW District Sammamish Event [${year}wasam]',
  '${year}wasno': '${year} PNW District Glacier Peak Event [${year}wasno]',
  '${year}wayak': '${year} PNW District SunDome Event [${year}wayak]',
  '${year}week0': '${year} Week 0 [${year}week0]',
  '${year}wila': '${year} Seven Rivers Regional [${year}wila]',
  '${year}wilrec':
      '${year} Lakeshore Robotics Endurance Competition [${year}wilrec]',
  '${year}wimi': '${year} Wisconsin Regional [${year}wimi]',
  '${year}wimu': '${year} Phantom Lakes Regional [${year}wimu]',
  '${year}wisc': '${year} Wisconsin State Championship [${year}wisc]',
  '${year}wiss': '${year} Sussex Scrimmage [${year}wiss]',
  '${year}witw': '${year} TWIST [${year}witw]',
  '${year}wiwi': '${year} WIWI [${year}wiwi]',
  '${year}wmri': '${year} West Michigan Robotics Invitational [${year}wmri]',
  '${year}xxmel': '${year} Melbourne Robotics Tournament [${year}xxmel]',
  '${year}xxsan': '${year} World Robot Contest Championships [${year}xxsan]',
};
