stat_description = {
    "OPR": "Offensive Power Rating - The average number of points a team contributes to their alliance's score per match.",
    "auto_points": "Points scored during the autonomous period.",
    "teleop_points": "Points scored during the teleoperated period.",
    "endgame_points": "Points scored during the endgame period.",
    "climbing_points": "Points earned from climbing activities.",
    "climb_success_rate": "Percentage of successful climbs.",
    "shooting_accuracy": "Accuracy of shooting attempts.",
    "cycles_per_match": "Average number of cycles completed per match.",
    "shoot_amount_total": "Total number of shots taken.",
    "shoots_from_X": "Shots taken from position X.",
    "shoots_from_Y": "Shots taken from position Y.",
    "total_cycles": "Total number of cycles completed.",
    "auto_shoot_amount": "Number of shots taken during autonomous.",
    "auto_shoot_points": "Points scored from autonomous shooting.",
    "teleop_shoot_amount": "Number of shots taken during teleop.",
    "teleop_shoot_points": "Points scored from teleop shooting.",
    "feed_amount": "Number of game pieces fed into the robot.",
    "intake_amount": "Number of game pieces intaken.",
    "goes_under_trench": "Ability to go under the trench obstacle.",
    "goes_over_bump": "Ability to go over the bump obstacle.",
    "climb_side": "Preferred side for climbing.",
    "death_rate": "Frequency of robot failures or 'deaths' during matches.",
    "coopertition": "Cooperation with opposing alliance for bonus points.",
    "mobility": "Ability to move from starting position.",
    "match_count": "Number of matches played.",
    "rank": "Current event ranking.",
    "simulated_rp": "Simulated ranking points based on predicted performance.",
    "simulated_rank": "Simulated rank based on predicted performance."
}